notes/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index', as: 'home'
  get 'about'=>'pages#about', as: 'about'
  resources :posts
end

notes/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

notes/app/models/post.rb
class Post < ApplicationRecord
  validates :title,presence:true,length:{minimum:3}
end

notes/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

notes/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

notes/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
    @title='about us'
    @content='this is the about page'
  end
end

notes/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  def index
    @posts=Post.all
  end

  def show
    @post=Post.find(params[:id])
  end

  def new
    @post=Post.new
  end

  def create
    #render plain: params[:post].inspect
    @post=Post.new(post_params)
    if(@post.save)
      redirect_to posts_path
    else
      render 'new'
    end
  end

  def edit
    show
  end

  def update
    show
    if(@post.update(post_params))
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    show
    @post.delete
    redirect_to posts_path

  end

  private def post_params
    params.require(:post).permit(:title,:body)
  end
end

notes/app/helpers/application_helper.rb
module ApplicationHelper
end

notes/app/helpers/pages_helper.rb
module PagesHelper
end

notes/app/helpers/posts_helper.rb
module PostsHelper
end

notes/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>notes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <%= link_to "notes", home_path, class: 'navbar-brand' %>

      <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0"></ul>
        <ul class="navbar-nav navbar-right">
          <li class="<%= 'nav-item active' if current_page?(new_post_path) %>"><%= link_to "create note", new_post_path, class: 'nav-link' %></li>

            <% if user_signed_in? %>
              <li class="<%= 'nav-item active' if current_page?(edit_user_registration_path) %>"><%= link_to current_user.email, edit_user_registration_path, class: 'nav-link' %></li>
              <%= link_to 'logout', destroy_user_session_path, method: :delete, class: 'nav-link' %>
            <% else %>
              <%= link_to 'sign up', new_user_registration_path, :class => 'nav-link' %>
              <%= link_to 'login', new_user_session_path, :class => 'nav-link' %>
            <% end %>

        </ul>
      </div>
    </nav>

    <div class="container-fluid">
      <% if notice %>
        <br>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <br>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

notes/app/views/pages/about.html.erb
<h1><%=@title%></h1>
<p><%=@content%></p>

notes/app/views/posts/edit.html.erb
<br>
<%=form_for :post,url: post_path(@post),method: :patch do |k|%>
  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>
  <p>
    <%=k.label :title%><br>
    <%=k.text_field(:title,{:class=>'form-control mr-sm-2'})%>
  </p>
  <p>
    <%=k.label :body%>:<br>
    <%=k.text_area(:body,{:class=>'form-control mr-sm-2'})%>
  </p>
  <p>
    <%=k.submit('edit note', {:class=>'btn btn-outline-info'})%>
  </p>
<%end%>

notes/app/views/posts/index.html.erb
<br>
<% @posts.in_groups_of(4, false).each do |group| %>
  <div class='row'>
    <% group.each do |k| %>
      <div class='col-sm-6'>
        <div class="card bg-light border-info mb-3">
          <div class="card-body">
            <h4 class="card-title"><%=k.title%></h4>
            <p class="card-text"><%=k.body%></p>
            <%= link_to "read more",post_path(k),:class=>'btn btn-outline-info'%>
            <%= link_to "delete",post_path(k),method: :delete,data:{confirm:'are you sure?'},:class=>'btn btn-outline-info' %>
          </div>
        </div>
        <br>
      </div>
    <% end %>
  </div>
<% end %>

notes/app/views/posts/new.html.erb
<br>
<%=form_for :post,url: posts_path do |k|%>
  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>
  <p>
    <%=k.label :title%><br>
    <%=k.text_field(:title,{:class=>'form-control mr-sm-2'})%>
  </p>
  <p>
    <%=k.label :body%><br>
    <%=k.text_area(:body,{:class=>'form-control mr-sm-2'})%>
  </p>
  <p>
    <%=k.submit('create note', {:class=>'btn btn-outline-info'})%>
  </p>
<%end%>

notes/app/views/posts/show.html.erb
<br>
<h2><%=@post.title%></h2>
<p><%=@post.body%></p>
<hr>
<%= link_to "edit",edit_post_path(@post),:class=>'btn btn-outline-info' %>